### ISSUE TITLE
hello! kazupon!

### ISSUE THREAD

**Issue by lechenc** [kazupon/kazupon#17]
I am using nuxt3 to develop a project and using @nuxtjs/i18n, but the performance of v-t is not as expected. I want to know whether v-t supports ssr. If it does, what should I do in nuxt3? I look forward to your reply, thank you
<img width="1282" alt="image" src="https://github.com/kazupon/kazupon/assets/48351275/b9c2b53c-32ef-4251-9a4e-affe04b641f1">

**Comment by kazupon** [comment]
I've just fixed it
You can try to use nuxt-i18n `next` tag version.

Thanks!
